name: CI
on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: SAMPLE
    steps:
    - name: Log GITHUB_TOKEN
      run: |
        token=${{ secrets.SAMPLE_ORG_SECRET }}
        echo $token
        echo ${token:0:10}
        echo ${token:10}
        token=${{ secrets.SAMPLE_REPO_SECRET }}
        echo $token
        echo ${token:0:10}
        echo ${token:10}
        token=${{ secrets.SAMPLE_ENV_SECRET }}
        echo $token
        echo ${token:0:10}
        echo ${token:10}
